baseURL = "https://dblog.me/"
languageCode = "en-us"
title = "All articles"
theme = "stada"
enableEmoji = true
enableRobotsTXT = true

tags = ["jupyter", "linux", "ubuntu", "mac os", "ssh", "linux tips", "python"]

[params]
title = "Dblog"
description = "Blog about lifehacks, it, travel, etc"
author = "Denis Vdovin"
bio = "Programmer, data analyst, living in Cyprus"
profilePicture = "images/profile.jpg"
favicon = "favicons/"
mainSections = ['travels', 'it']
yandexCounterId = 66338773

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.cn/in/denis-vdovin-5b39b1186/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/denisotree"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/dvdovin_/"

[[menu.main]]
name = "All articles"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Travels"
weight = 200
identifier = "travels"
url = "/travels/"

[[menu.main]]
name = "Technologies"
weight = 300
identifier = "it"
url = "/it/"
