baseURL = "https://dblog.me/"
languageCode = "en-us"
title = "Все статьи"
theme = "stada"
enableEmoji = true
enableRobotsTXT = true

googleAnalytics = ""

[params]
title = "Denis Vdovin"
author = "Denis Vdovin"
desctiption = "Denis Vdovin personal blog"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ['travels', 'it']
images = ["images/site-feature-image.png"]

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.cn/in/denis-vdovin-5b39b1186/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/denisotree"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/dvdovin_/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:denisotree@gmail.com"

[menu]

  [[menu.main]]
  name = "All articles"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Travels"
  weight = 200
  identifier = "travels"
  url = "/travels/"

  [[menu.main]]
  name = "Technologies"
  weight = 300
  identifier = "it"
  url = "/it/"
