[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.99.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.99.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.99.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.99.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = '''
    public,
	max-age=86400
	'''
[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = '''
    public,
	max-age=86400
	'''
[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = '''
    public,
	max-age=86400
	'''
[[headers]]
  for = "/fonts/*"
  [headers.values]
    cache-control = '''
    public,
	max-age=86400
	'''
[[headers]]
  for = "/favicons/*"
  [headers.values]
    cache-control = '''
    public,
	max-age=86400
	'''

